defmodule Medishop.Repo.Migrations.AddInventoryTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:location_inventories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_available, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id,
          references(:locations,
            column: :id,
            name: "location_inventories_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "location_inventories_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:location_inventories, [:location_id, :product_id],
             name: "location_inventories_unique_location_product_index"
           )
  end

  def down do
    drop_if_exists unique_index(:location_inventories, [:location_id, :product_id],
                     name: "location_inventories_unique_location_product_index"
                   )

    drop constraint(:location_inventories, "location_inventories_location_id_fkey")

    drop constraint(:location_inventories, "location_inventories_product_id_fkey")

    drop table(:location_inventories)
  end
end
