defmodule Medishop.Repo.Migrations.AddShopDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :order_number, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :subtotal, :decimal, null: false
      add :total, :decimal, null: false
      add :notes, :text
      add :placed_at, :utc_datetime_usec
      add :confirmed_at, :utc_datetime_usec
      add :shipped_at, :utc_datetime_usec
      add :delivered_at, :utc_datetime_usec
      add :cancelled_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id,
          references(:locations,
            column: :id,
            name: "orders_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "orders_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:orders, [:order_number], name: "orders_unique_order_number_index")

    create table(:order_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :bigint, null: false
      add :unit_price, :decimal, null: false
      add :line_total, :decimal, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_items_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "order_items_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:carts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id,
          references(:locations,
            column: :id,
            name: "carts_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:carts, [:location_id], name: "carts_unique_cart_per_location_index")

    create table(:cart_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :bigint, null: false, default: 1
      add :price_at_addition, :decimal, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :cart_id,
          references(:carts,
            column: :id,
            name: "cart_items_cart_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "cart_items_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:cart_items, [:cart_id, :product_id],
             name: "cart_items_unique_cart_item_per_product_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cart_items, [:cart_id, :product_id],
                     name: "cart_items_unique_cart_item_per_product_index"
                   )

    drop constraint(:cart_items, "cart_items_cart_id_fkey")

    drop constraint(:cart_items, "cart_items_product_id_fkey")

    drop table(:cart_items)

    drop_if_exists unique_index(:carts, [:location_id],
                     name: "carts_unique_cart_per_location_index"
                   )

    drop constraint(:carts, "carts_location_id_fkey")

    drop table(:carts)

    drop constraint(:order_items, "order_items_order_id_fkey")

    drop constraint(:order_items, "order_items_product_id_fkey")

    drop table(:order_items)

    drop_if_exists unique_index(:orders, [:order_number],
                     name: "orders_unique_order_number_index"
                   )

    drop constraint(:orders, "orders_location_id_fkey")

    drop constraint(:orders, "orders_user_id_fkey")

    drop table(:orders)
  end
end
