defmodule Medishop.Repo.Migrations.FinalizeVoucherSystem do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:order_items) do
      modify :product_id, :uuid, null: true
      add :description, :text
    end
  end

  def down do
    alter table(:order_items) do
      remove :description
      modify :product_id, :uuid, null: false
    end
  end
end
