defmodule Medishop.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stock_reconciliations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "in_progress"
      add :started_at, :utc_datetime_usec, null: false
      add :completed_at, :utc_datetime_usec
      add :notes, :text
      add :total_items_checked, :bigint, null: false, default: 0
      add :total_discrepancies, :bigint, null: false, default: 0
      add :total_adjustments_made, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id,
          references(:locations,
            column: :id,
            name: "stock_reconciliations_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:reconciliation_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :system_quantity, :bigint, null: false
      add :physical_quantity, :bigint, null: false
      add :adjustment_reason, :text
      add :adjustment_notes, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :reconciliation_id,
          references(:stock_reconciliations,
            column: :id,
            name: "reconciliation_items_reconciliation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "reconciliation_items_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :location_inventory_id,
          references(:location_inventories,
            column: :id,
            name: "reconciliation_items_location_inventory_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inventory_event_id,
          references(:inventory_events,
            column: :id,
            name: "reconciliation_items_inventory_event_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:reconciliation_items, [:reconciliation_id, :product_id],
             name: "reconciliation_items_unique_reconciliation_product_index"
           )

    alter table(:products) do
      add :unit_of_measure, :text
      add :storage_location, :text
      add :active_ingredient, :text
      add :strength, :text
    end
  end

  def down do
    alter table(:products) do
      remove :strength
      remove :active_ingredient
      remove :storage_location
      remove :unit_of_measure
    end

    drop_if_exists unique_index(:reconciliation_items, [:reconciliation_id, :product_id],
                     name: "reconciliation_items_unique_reconciliation_product_index"
                   )

    drop constraint(:reconciliation_items, "reconciliation_items_reconciliation_id_fkey")

    drop constraint(:reconciliation_items, "reconciliation_items_product_id_fkey")

    drop constraint(:reconciliation_items, "reconciliation_items_location_inventory_id_fkey")

    drop constraint(:reconciliation_items, "reconciliation_items_inventory_event_id_fkey")

    drop table(:reconciliation_items)

    drop constraint(:stock_reconciliations, "stock_reconciliations_location_id_fkey")

    drop table(:stock_reconciliations)
  end
end
