defmodule Medishop.Repo.Migrations.AddProductsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sku, :text, null: false
      add :title, :text, null: false
      add :description, :text
      add :images, {:array, :text}, default: []
      add :price, :decimal, null: false
      add :active, :boolean, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:products, [:sku], name: "products_unique_sku_index")
  end

  def down do
    drop_if_exists unique_index(:products, [:sku], name: "products_unique_sku_index")

    drop table(:products)
  end
end
