defmodule Medishop.Repo.Migrations.AddOrganizationsAndInventory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :active, :boolean, null: false, default: false
      add :is_test_organization, :boolean, null: false, default: false
      add :invoice_email, :text
      add :billing_address, :map
      add :tax_id, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:organization_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :org_roles, {:array, :text}, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "organization_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:organization_memberships, [:user_id, :organization_id],
             name: "organization_memberships_unique_user_organization_index"
           )

    create table(:organization_location_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_membership_id,
          references(:organization_memberships,
            column: :id,
            name: "organization_location_memberships_organization_membership_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :location_id, :uuid, null: false
    end

    create table(:locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:organization_location_memberships) do
      modify :location_id,
             references(:locations,
               column: :id,
               name: "organization_location_memberships_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(
             :organization_location_memberships,
             [:organization_membership_id, :location_id],
             name: "org_location_membership_unique_idx"
           )

    alter table(:locations) do
      add :name, :text, null: false
      add :address, :map, null: false
      add :contact_number, :text, null: false
      add :store, :boolean, default: false
      add :test_location, :boolean, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "locations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:location_inventories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_available, :bigint, null: false, default: 0

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id,
          references(:locations,
            column: :id,
            name: "location_inventories_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "location_inventories_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:location_inventories, [:location_id, :product_id],
             name: "location_inventories_unique_location_product_index"
           )
  end

  def down do
    drop_if_exists unique_index(:location_inventories, [:location_id, :product_id],
                     name: "location_inventories_unique_location_product_index"
                   )

    drop constraint(:location_inventories, "location_inventories_location_id_fkey")

    drop constraint(:location_inventories, "location_inventories_product_id_fkey")

    drop table(:location_inventories)

    drop constraint(:locations, "locations_organization_id_fkey")

    alter table(:locations) do
      remove :organization_id
      remove :updated_at
      remove :created_at
      remove :test_location
      remove :store
      remove :contact_number
      remove :address
      remove :name
    end

    drop_if_exists unique_index(
                     :organization_location_memberships,
                     [:organization_membership_id, :location_id],
                     name: "org_location_membership_unique_idx"
                   )

    drop constraint(
           :organization_location_memberships,
           "organization_location_memberships_location_id_fkey"
         )

    alter table(:organization_location_memberships) do
      modify :location_id, :uuid
    end

    drop table(:locations)

    drop constraint(
           :organization_location_memberships,
           "organization_location_memberships_organization_membership_id_fkey"
         )

    drop table(:organization_location_memberships)

    drop_if_exists unique_index(:organization_memberships, [:user_id, :organization_id],
                     name: "organization_memberships_unique_user_organization_index"
                   )

    drop constraint(:organization_memberships, "organization_memberships_user_id_fkey")

    drop constraint(:organization_memberships, "organization_memberships_organization_id_fkey")

    drop table(:organization_memberships)

    drop table(:organizations)
  end
end
