defmodule Medishop.Repo.Migrations.UpdateCartOrderForVouchers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :discount_total, :decimal, null: false, default: "0.00"

      add :voucher_id,
          references(:vouchers,
            column: :id,
            name: "orders_voucher_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:carts) do
      add :discount_total, :decimal, null: false, default: "0.00"

      add :voucher_id,
          references(:vouchers,
            column: :id,
            name: "carts_voucher_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:carts, "carts_voucher_id_fkey")

    alter table(:carts) do
      remove :voucher_id
      remove :discount_total
    end

    drop constraint(:orders, "orders_voucher_id_fkey")

    alter table(:orders) do
      remove :voucher_id
      remove :discount_total
    end
  end
end
