defmodule Medishop.Repo.Migrations.AddSuppliers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:suppliers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :address, :text
      add :sage_id, :text
      add :contact_email, :text
      add :contact_number, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:product_suppliers, primary_key: false) do
      add :product_id,
          references(:products,
            column: :id,
            name: "product_suppliers_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :supplier_id,
          references(:suppliers,
            column: :id,
            name: "product_suppliers_supplier_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:product_suppliers, "product_suppliers_product_id_fkey")

    drop constraint(:product_suppliers, "product_suppliers_supplier_id_fkey")

    drop table(:product_suppliers)

    drop table(:suppliers)
  end
end
