defmodule Medishop.Repo.Migrations.AddResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vouchers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :code, :citext, null: false
      add :discount_type, :text, null: false
      add :discount_value, :decimal, null: false
      add :min_purchase_type, :text, default: "none"
      add :min_purchase_value, :decimal
      add :usage_limit_total, :bigint
      add :usage_limit_per_location, :bigint
      add :apply_to_shipping, :boolean, default: false
      add :combinable, :boolean, default: false
      add :tax_application, :text, default: "after_tax"
      add :start_date, :date
      add :end_date, :date
      add :active, :boolean, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:vouchers, [:code], name: "vouchers_unique_code_index")

    create table(:voucher_redemptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :discount_amount, :decimal, null: false

      add :redeemed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :voucher_id,
          references(:vouchers,
            column: :id,
            name: "voucher_redemptions_voucher_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :order_id,
          references(:orders,
            column: :id,
            name: "voucher_redemptions_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :location_id,
          references(:locations,
            column: :id,
            name: "voucher_redemptions_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "voucher_redemptions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:voucher_products, primary_key: false) do
      add :voucher_id,
          references(:vouchers,
            column: :id,
            name: "voucher_products_voucher_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "voucher_products_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create table(:voucher_organizations, primary_key: false) do
      add :voucher_id,
          references(:vouchers,
            column: :id,
            name: "voucher_organizations_voucher_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "voucher_organizations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create table(:voucher_locations, primary_key: false) do
      add :voucher_id,
          references(:vouchers,
            column: :id,
            name: "voucher_locations_voucher_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :location_id,
          references(:locations,
            column: :id,
            name: "voucher_locations_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create table(:suppliers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :address, :text
      add :sage_id, :text
      add :contact_email, :text
      add :contact_number, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:product_suppliers, primary_key: false) do
      add :product_id,
          references(:products,
            column: :id,
            name: "product_suppliers_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :supplier_id,
          references(:suppliers,
            column: :id,
            name: "product_suppliers_supplier_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    alter table(:orders) do
      add :discount_total, :decimal, null: false, default: "0.00"

      add :voucher_id,
          references(:vouchers,
            column: :id,
            name: "orders_voucher_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:carts) do
      add :discount_total, :decimal, null: false, default: "0.00"

      add :voucher_id,
          references(:vouchers,
            column: :id,
            name: "carts_voucher_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:carts, "carts_voucher_id_fkey")

    alter table(:carts) do
      remove :voucher_id
      remove :discount_total
    end

    drop constraint(:orders, "orders_voucher_id_fkey")

    alter table(:orders) do
      remove :voucher_id
      remove :discount_total
    end

    drop constraint(:product_suppliers, "product_suppliers_product_id_fkey")

    drop constraint(:product_suppliers, "product_suppliers_supplier_id_fkey")

    drop table(:product_suppliers)

    drop table(:suppliers)

    drop constraint(:voucher_locations, "voucher_locations_voucher_id_fkey")

    drop constraint(:voucher_locations, "voucher_locations_location_id_fkey")

    drop table(:voucher_locations)

    drop constraint(:voucher_organizations, "voucher_organizations_voucher_id_fkey")

    drop constraint(:voucher_organizations, "voucher_organizations_organization_id_fkey")

    drop table(:voucher_organizations)

    drop constraint(:voucher_products, "voucher_products_voucher_id_fkey")

    drop constraint(:voucher_products, "voucher_products_product_id_fkey")

    drop table(:voucher_products)

    drop constraint(:voucher_redemptions, "voucher_redemptions_voucher_id_fkey")

    drop constraint(:voucher_redemptions, "voucher_redemptions_order_id_fkey")

    drop constraint(:voucher_redemptions, "voucher_redemptions_location_id_fkey")

    drop constraint(:voucher_redemptions, "voucher_redemptions_user_id_fkey")

    drop table(:voucher_redemptions)

    drop_if_exists unique_index(:vouchers, [:code], name: "vouchers_unique_code_index")

    drop table(:vouchers)
  end
end
