defmodule Medishop.Repo.Migrations.AddStripeCustomerIdToOrg do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :stripe_customer_id, :text
    end
  end

  def down do
    alter table(:organizations) do
      remove :stripe_customer_id
    end
  end
end
