defmodule Medishop.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inventory_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :quantity_change, :bigint, null: false
      add :batch_number, :text
      add :expiration_date, :date
      add :reference_type, :text
      add :reference_id, :uuid
      add :reason, :text
      add :occurred_at, :utc_datetime_usec, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :location_id,
          references(:locations,
            column: :id,
            name: "inventory_events_location_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "inventory_events_product_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:inventory_events, "inventory_events_location_id_fkey")

    drop constraint(:inventory_events, "inventory_events_product_id_fkey")

    drop table(:inventory_events)
  end
end
