defmodule Medishop.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:location_inventories) do
      remove :quantity_available
    end
  end

  def down do
    alter table(:location_inventories) do
      add :quantity_available, :bigint, null: false, default: 0
    end
  end
end
